# Generated by Django 4.1.3 on 2023-02-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('release_at', models.DateField(verbose_name='Release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Singer',
                'verbose_name_plural': 'Singers',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='SongsInAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Sequence number')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='albums.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='albums.song')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='albums.singer', verbose_name='Singer'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(through='albums.SongsInAlbum', to='albums.song', verbose_name='Songs'),
        ),
        migrations.AddConstraint(
            model_name='songsinalbum',
            constraint=models.UniqueConstraint(fields=('album', 'song'), name='songs_in_album_idx'),
        ),
        migrations.AddConstraint(
            model_name='songsinalbum',
            constraint=models.UniqueConstraint(fields=('album', 'number'), name='number_in_album_idx'),
        ),
    ]
